name: Build, Test, and Pack

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_config: ['Release', 'Debug']

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ matrix.build_config }}

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ matrix.build_config }}

    - name: Pack the nuget packages
      run: dotnet pack --no-restore --configuration ${{matrix.build_config}} -p:PackageVersion=5.0.4.${{ github.run_number }}-alpha --output ${{ github.workspace }}/pack

    - name: Upload the nuget packages
      uses: actions/upload-artifact@v4
      with:
        name: ENet.Managed-${{ matrix.build_config }}-${{ github.sha }}
        path: ${{ github.workspace }}/pack
        
        
